### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by cheetahbyte** [m-editor/molecule#11]
# fonts in editor
let's introduce font settings for molecule!

### example section for config
```yml
font: 
  family: Fira Code Nerd Font
  size: 14
  ligatures: true
``` 

> Should only affect the text editor area. Not the complete UI.
